---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
logging.events.log: ['warning', 'error', 'fatal', 'info', 'reporting']

## X-Pack settings
## see https://www.elastic.co/guide/en/kibana/current/security-settings-kb.html
#
# xpack.security.enabled: false
# xpack.monitoring.ui.container.elasticsearch.enabled: true

#
# Enable data collection from Kibana NodeJS server for kibana dashboards to be featured in Monitoring
monitoring.kibana.collection.enabled: true
monitoring.ui.container.elasticsearch.enabled: true;

## Custom configuration
#
elasticsearch.username: "kibanaserver"
elasticsearch.password: "kibanaserver"

elasticsearch.ssl.verificationMode: certificate
elasticsearch.ssl.certificateAuthorities: /usr/share/kibana/ssl/root-ca.pem

#searchguard.cookie.password: "123567818187654rwrwfsfshdhdhtegdhfzftdhncn"
